name: cd-azure

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/cd-azure.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, so we can generate version off of tags/commits
      
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: ./build-push.sh
        working-directory: ./api

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'production'
    steps:
      - uses: actions/checkout@v4

      # Login to Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup Terraform
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./api/azure-app

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./api/azure-app

      # Plan Terraform changes
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./api/azure-app
        env:
          TF_LOG: INFO

      # Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./api/azure-app

      # Deploy to Azure Web App
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'tjm-gh-actions-web-api'
          images: 'terryjmitchell/actions-web:latest'
          resource-group-name: gh-actions
