name: cd-on-deploy

on:
  deployment:

jobs:
  alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Alert      
        run: | 
          echo "Deployment event received. You can integrate with alerting services here."
          echo "${{ toJson(github.event) }}"