name: upper-image

on:
  push:
    paths:
      - ".github/workflows/upper-image.yaml"
      - "upper/**"
  workflow_dispatch: # optional manual trigger

permissions:
  packages: write
  contents: read

jobs:  
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper . 
        working-directory: ./upper
      - name: test it
        run: docker container run upper hello terry
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/${{ github.repository_owner }}/upper:latest
      - run: docker tag upper ghtc.io/${{ github.repository_owner }}/upper:${{ github.ref_name}}
      - run: docker push ghcr.io/${{ github.repository_owner }}/upper:latest
      - run: docker push ghcr.io/${{ github.repository_owner }}/upper:${{ github.ref_name}}
