name: upper-xplat

on:
  push:
    paths:
      - ".github/workflows/upper-cross.yaml"
      - "upper/**"
  workflow_dispatch: # optional manual trigger

jobs:
  capture:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          #go-version-file: ./upper/go.mod
          cache-dependency-path: ./upper/go.sum
      - run: ./build.xplat.sh
      - uses: softprops/action-gh-release@v1
        with:
          files: ./upper/bin/upper*
          body: "Binaries for the upper (go) command line tool"
          tag_name: ${{ github.ref_name }}
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: ./upper/bin/upper*
      #     name: build

