name: upper-capture

on:
  push:
    paths:
      - ".github/workflows/upper-capture.yaml"
      - "upper/**"
  workflow_dispatch: # optional manual trigger

jobs:
  capture:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./upper/go.mod
          cache-dependency-path: ./upper/go.sum
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
      - uses: actions/upload-artifact@v4
        with:
          path: ./upper/upper
          name: "build-${{ matrix.os }}"
