name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yaml"
      - "upper/**"
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - run: pwd && ls -al
      - run: go version
      - uses: actions/setup-go@v4
        with:
          # go-version: '1.22'
          go-version-file: ./upper/go.mod
      - run: go version
      - run: |
          ls
          go build
          ls
          go test
          ./upper foo the bar
        working-directory: ./upper
        name: build and test upper


