name: upper-capture

on:
  push:
    paths:
      - ".github/workflows/upper-capture.yaml"
      - "upper/**"
  workflow_dispatch: # optional manual trigger

jobs:
  capture:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./upper/go.mod
          cache-dependency-path: ./upper/go.sum
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
